function ScriptLoad() {
	document.body.style.backgroundColor = "#ffd480";
	let h1 = document.createElement("h1");
	let text_h1 = document.createTextNode("Решаване на квадратно уравнение");
	h1.setAttribute("id","center");
	h1.appendChild(text_h1);
	document.body.appendChild(h1);
	document.body.appendChild(document.createElement("br"));
	let div = document.createElement("div");
	document.body.appendChild(div);
	let paragraph = document.createElement("p");
	let text1 = document.createTextNode("Въведете коефициентите пред неизвестните променливи в даденото уравнение!");
	paragraph.style.textAlign = "center";
	paragraph.style.fontSize = "16pt";
	paragraph.appendChild(text1);
	div.appendChild(paragraph);
	let div2 = document.createElement("div");
	document.body.appendChild(div2);
	let form_equation = document.createElement("form");
	form_equation.setAttribute("name","equation");
	form_equation.style.textAlign = "center";
	form_equation.style.fontSize = "16pt";
	let a = document.createElement("input");
	a.setAttribute("type","number");
	a.setAttribute("name","a");
	a.setAttribute("id","a");
	a.style.width = "30px";
	form_equation.appendChild(a);
	let x_1 = document.createTextNode("x");
	form_equation.appendChild(x_1);
	let square = document.createElement("sup");
	form_equation.appendChild(square);
	let two = document.createTextNode("2");
	square.appendChild(two);
	let plus1 = document.createTextNode(" + ");
	form_equation.appendChild(plus1);
	let b = document.createElement("input");
	b.setAttribute("type","number");
	b.setAttribute("name","b");
	b.setAttribute("ïd","b");
	b.style.width = "30px";
	form_equation.appendChild(b);
	let x_2 = document.createTextNode("x");
	form_equation.appendChild(x_2);
	let plus2 = document.createTextNode(" + ");
	form_equation.appendChild(plus2);
	let c = document.createElement("input");
	c.setAttribute("type","number");
	c.setAttribute("name","c");
	c.setAttribute("id","c");
	c.style.width = "30px";
	form_equation.appendChild(c);
	let eq = document.createTextNode(" = ");
	form_equation.appendChild(eq);
	let zero = document.createTextNode("0");
	form_equation.appendChild(zero);
	form_equation.appendChild(document.createElement("br"));
	form_equation.appendChild(document.createElement("br"));
	let calculate = document.createElement("input");
	calculate.setAttribute("type","button");
	calculate.setAttribute("name","calculate");
	calculate.setAttribute("id","calculate");
	calculate.setAttribute("value","Изчисли");
	form_equation.appendChild(calculate);
	div2.appendChild(form_equation);
	let div3 = document.createElement("div");
	let paragraph2 = document.createElement("p");
	paragraph2.setAttribute("id","result");
	div3.appendChild(paragraph2);
	document.body.appendChild(div3);
}